title: Beyond Algos
description: Written in Sydney by a human, for humans. A no-nonsense guide to engineering a trading platform and navigating financial markets.
url: "https://jplemoussu.github.io"
baseurl: "/beyond-algos"

theme: minima
minima:
  skin: classic

permalink: /:title/

header_pages:
  - about.md
